# Generated by Django 3.2.20 on 2023-10-02 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('d_address_line_1', models.CharField(blank=True, max_length=90, null=True)),
                ('d_address_line_2', models.CharField(blank=True, max_length=90, null=True)),
                ('d_city', models.CharField(blank=True, max_length=40, null=True)),
                ('d_post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('d_country', django_countries.fields.CountryField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
