# Generated by Django 3.2.20 on 2023-10-02 23:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='d_country',
            field=django_countries.fields.CountryField(blank=True, max_length=80, null=True),
        ),
    ]
