# Generated by Django 3.2.20 on 2023-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_rename_user_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(max_length=20),
        ),
    ]
