# Generated by Django 3.2.20 on 2023-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_new',
            new_name='new_arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(default=False),
        ),
    ]
