# Generated by Django 3.2.20 on 2023-10-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
