# Generated by Django 3.2.20 on 2023-10-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20231019_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=255),
        ),
    ]
